CREATE TABLE audience (
    audience_id     integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    room_name       varchar(10) UNIQUE NOT NULL,
    amount_of_seats integer NOT NULL
);

CREATE TABLE roomtype (
    room_type_id   integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    room_type_name varchar NOT NULL UNIQUE
);

CREATE TABLE audience_roomtype (
    room_type_id integer NOT NULL REFERENCES roomtype (room_type_id),
    audience_id  integer NOT NULL REFERENCES audience (audience_id),
    PRIMARY KEY (room_type_id, audience_id)
);


CREATE TABLE students_group (
    students_group_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    group_name        varchar(10) NOT NULL UNIQUE,
    students_count    integer NOT NULL
);

CREATE TABLE professor (
    professor_id   BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE discipline (
    discipline_id      integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    discipline_name    varchar(40) NOT NULL,
    optimal_room_type integer[],

    -- часы
    contact_hours      float NOT NULL,
    independent_hours  float,
    course_hours       float NOT NULL,
    seminar_hours      float NOT NULL,
    lab_hours          float NOT NULL
);


CREATE TABLE professor_discipline (
    professor_id  integer NOT NULL REFERENCES professor (professor_id),
    discipline_id integer NOT NULL REFERENCES discipline (discipline_id),
    PRIMARY KEY (professor_id, discipline_id)
);


CREATE TABLE schedule (
    id integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    students_group_id integer NOT NULL REFERENCES students_group(students_group_id),
    day_of_week  integer NOT NULL,
    pair_number integer NOT NULL,
    audience_id   integer NOT NULL REFERENCES audience (audience_id),
    discipline_id integer NOT NULL REFERENCES discipline (discipline_id),
    professor_id  integer NOT NULL REFERENCES professor (professor_id)
);

CREATE TABLE algorithm_runs (
    id                 BIGSERIAL PRIMARY KEY,
    algorithm_name     VARCHAR(50) NOT NULL,   -- 'GENETIC', 'GREEDY', 'SIMULATED_ANNEALING'...
    parameters         JSONB,                  -- гиперпараметры конкретного запуска
    started_at         TIMESTAMP NOT NULL DEFAULT now(),
    execution_time_ms  BIGINT,
    fitness_score      DOUBLE PRECISION,
    extra_metrics      JSONB                   -- всё, что не влезает в стандартные колонки
);




--- TEST DATA

INSERT INTO roomtype (room_type_id, room_type_name) VALUES
(1, 'lecture'),
(2, 'seminar'),
(3, 'lab');

INSERT INTO audience (audience_id, room_name, amount_of_seats) VALUES
(1, 'A101', 30),
(2, 'A102', 24),
(3, 'B201', 50),
(4, 'B202', 18),
(5, 'C301', 80),
(6, 'C302', 12);

INSERT INTO audience_roomtype (room_type_id, audience_id) VALUES
(1, 1),
(1, 2),
(1, 3),
(2, 4),
(1, 5),
(2, 5),
(3, 5),
(2, 6);

INSERT INTO students_group (students_group_id, group_name, students_count) VALUES
(1, 'CS-101', 28),
(2, 'CS-102', 24),
(3, 'MATH-201', 18),
(4, 'PHY-301', 32),
(5, 'BIO-401', 20);

INSERT INTO professor (professor_id, name) VALUES
(1, 'Ivan Petrov'),
(2, 'Olga Smirnova'),
(3, 'Maksim Ivanov'),
(4, 'Anna Volkova'),
(5, 'Dmitry Kuznetsov'),
(6, 'Elena Sokolova'),
(7, 'Sergey Pavlov');

INSERT INTO discipline
(discipline_id, discipline_name, optimal_room_type, contact_hours, independent_hours, course_hours, seminar_hours, lab_hours)
VALUES
(1, 'Discrete Math', ARRAY[1], 64, 32, 48, 16, 0),
(2, 'Databases', ARRAY[1,3], 72, 24, 36, 24, 12),
(3, 'Algorithms', ARRAY[1], 80, 40, 56, 24, 0),
(4, 'Physics', ARRAY[1,2], 96, 48, 32, 32, 32),
(5, 'Programming', ARRAY[1,3], 120, 48, 48, 24, 48),
(6, 'Statistics', ARRAY[1,2], 48, 24, 32, 16, 0),
(7, 'English', ARRAY[2], 36, 20, 36, 0, 0),
(8, 'Networks', ARRAY[1,3], 60, 24, 24, 12, 24);

INSERT INTO professor_discipline (professor_id, discipline_id) VALUES
(1, 1),
(2, 2),
(3, 3),
(4, 4),
(5, 5),
(6, 6),
(7, 7),
(2, 8),
(5, 2),
(6, 5);

INSERT INTO schedule
(id, students_group_id, day_of_week, pair_number, audience_id, discipline_id, professor_id)
VALUES
(1, 1, 1, 1, 1, 1, 1),
(2, 1, 2, 2, 2, 2, 2),
(3, 1, 3, 1, 3, 3, 3),
(4, 2, 1, 2, 4, 4, 4),
(5, 2, 2, 3, 5, 5, 5),
(6, 2, 4, 1, 1, 6, 6),
(7, 3, 1, 1, 2, 7, 7),
(8, 3, 3, 2, 3, 8, 2),
(9, 4, 2, 1, 5, 2, 1),
(10, 4, 4, 2, 6, 1, 3),
(11, 5, 1, 3, 3, 4, 4),
(12, 5, 5, 1, 1, 5, 5);

INSERT INTO algorithm_runs
(id, algorithm_name, parameters, execution_time_ms, fitness_score, extra_metrics)
VALUES
(1, 'GENETIC', '{"pop_size":200,"mutation_rate":0.08}'::jsonb, 1840, 0.91, '{"conflicts":3}'::jsonb),
(2, 'GREEDY', '{"strategy":"first_fit"}'::jsonb, 120, 0.73, '{"conflicts":12}'::jsonb),
(3, 'SIMULATED_ANNEALING', '{"temp":1000,"cooling":0.95}'::jsonb, 5320, 0.88, '{"conflicts":5}'::jsonb);



























